// src/utils/sampleData.js
export const sampleLeads = [
  {
    id: '1',
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1 (555) 123-4567',
    company: 'Acme Inc',
    city: 'New York',
    state: 'NY',
    source: 'website',
    status: 'contacted',
    score: 75,
    lead_value: 2500,
    is_qualified: true,
    last_activity_at: new Date('2023-05-15'),
    createdAt: new Date('2023-05-10')
  },
  {
    id: '2',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@example.com',
    phone: '+1 (555) 987-6543',
    company: 'XYZ Corp',
    city: 'Los Angeles',
    state: 'CA',
    source: 'facebook_ads',
    status: 'new',
    score: 45,
    lead_value: 1200,
    is_qualified: false,
    last_activity_at: null,
    createdAt: new Date('2023-05-12')
  },
  {
    id: '3',
    first_name: 'Robert',
    last_name: 'Johnson',
    email: 'robert.j@example.com',
    phone: '+1 (555) 456-7890',
    company: 'Tech Solutions',
    city: 'Chicago',
    state: 'IL',
    source: 'google_ads',
    status: 'qualified',
    score: 85,
    lead_value: 5000,
    is_qualified: true,
    last_activity_at: new Date('2023-05-14'),
    createdAt: new Date('2023-05-05')
  },
  {
    id: '4',
    first_name: 'Sarah',
    last_name: 'Williams',
    email: 'sarah.w@example.com',
    phone: '+1 (555) 234-5678',
    company: 'Design Studio',
    city: 'Austin',
    state: 'TX',
    source: 'referral',
    status: 'won',
    score: 95,
    lead_value: 7500,
    is_qualified: true,
    last_activity_at: new Date('2023-05-18'),
    createdAt: new Date('2023-04-28')
  },
  {
    id: '5',
    first_name: 'Michael',
    last_name: 'Brown',
    email: 'michael.b@example.com',
    phone: '+1 (555) 876-5432',
    company: 'Finance Corp',
    city: 'Boston',
    state: 'MA',
    source: 'events',
    status: 'lost',
    score: 30,
    lead_value: 3000,
    is_qualified: false,
    last_activity_at: new Date('2023-05-08'),
    createdAt: new Date('2023-05-01')
  },
  {
    id: '6',
    first_name: 'Emily',
    last_name: 'Davis',
    email: 'emily.d@example.com',
    phone: '+1 (555) 345-6789',
    company: 'Marketing Pros',
    city: 'Seattle',
    state: 'WA',
    source: 'website',
    status: 'contacted',
    score: 60,
    lead_value: 1800,
    is_qualified: true,
    last_activity_at: new Date('2023-05-16'),
    createdAt: new Date('2023-05-09')
  },
  {
    id: '7',
    first_name: 'David',
    last_name: 'Wilson',
    email: 'david.w@example.com',
    phone: '+1 (555) 765-4321',
    company: 'Consulting Group',
    city: 'Denver',
    state: 'CO',
    source: 'facebook_ads',
    status: 'new',
    score: 40,
    lead_value: 2200,
    is_qualified: false,
    last_activity_at: null,
    createdAt: new Date('2023-05-17')
  },
  {
    id: '8',
    first_name: 'Lisa',
    last_name: 'Taylor',
    email: 'lisa.t@example.com',
    phone: '+1 (555) 543-2167',
    company: 'Law Partners',
    city: 'Miami',
    state: 'FL',
    source: 'referral',
    status: 'qualified',
    score: 80,
    lead_value: 4200,
    is_qualified: true,
    last_activity_at: new Date('2023-05-13'),
    createdAt: new Date('2023-05-03')
  },
  {
    id: '9',
    first_name: 'James',
    last_name: 'Anderson',
    email: 'james.a@example.com',
    phone: '+1 (555) 654-3210',
    company: 'Tech Innovators',
    city: 'San Francisco',
    state: 'CA',
    source: 'google_ads',
    status: 'contacted',
    score: 70,
    lead_value: 3500,
    is_qualified: true,
    last_activity_at: new Date('2023-05-11'),
    createdAt: new Date('2023-05-06')
  },
  {
    id: '10',
    first_name: 'Amanda',
    last_name: 'Thomas',
    email: 'amanda.t@example.com',
    phone: '+1 (555) 432-1098',
    company: 'Creative Agency',
    city: 'Portland',
    state: 'OR',
    source: 'events',
    status: 'new',
    score: 50,
    lead_value: 2800,
    is_qualified: false,
    last_activity_at: null,
    createdAt: new Date('2023-05-15')
  },
  {
    id: '11',
    first_name: 'Daniel',
    last_name: 'Jackson',
    email: 'daniel.j@example.com',
    phone: '+1 (555) 321-0987',
    company: 'Software Solutions',
    city: 'Atlanta',
    state: 'GA',
    source: 'website',
    status: 'qualified',
    score: 90,
    lead_value: 6000,
    is_qualified: true,
    last_activity_at: new Date('2023-05-19'),
    createdAt: new Date('2023-04-30')
  },
  {
    id: '12',
    first_name: 'Jennifer',
    last_name: 'White',
    email: 'jennifer.w@example.com',
    phone: '+1 (555) 210-9876',
    company: 'Health Plus',
    city: 'Phoenix',
    state: 'AZ',
    source: 'facebook_ads',
    status: 'won',
    score: 100,
    lead_value: 8000,
    is_qualified: true,
    last_activity_at: new Date('2023-05-20'),
    createdAt: new Date('2023-04-25')
  }
];